### ISSUE TITLE
sweep_contex.h needs cstddef for NULL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [greenm01/poly2tri#28]
```
What steps will reproduce the problem?
1. Try to build with GCC 4.6.1

What is the expected output? What do you see instead?

Expected:
No compiler errors :)

Got:
In file included from ../poly2tri/sweep/sweep_context.cc:31:0:
../poly2tri/sweep/sweep_context.h: In constructor 
‘p2t::SweepContext::Basin::Basin()’:
../poly2tri/sweep/sweep_context.h:105:23: error: ‘NULL’ was not declared in 
this scope
../poly2tri/sweep/sweep_context.h: In member function ‘void 
p2t::SweepContext::Basin::Clear()’:
../poly2tri/sweep/sweep_context.h:111:17: error: ‘NULL’ was not declared in 
this scope
../poly2tri/sweep/sweep_context.h: In constructor 
‘p2t::SweepContext::EdgeEvent::EdgeEvent()’:
../poly2tri/sweep/sweep_context.h:123:34: error: ‘NULL’ was not declared in 
this scope

What version of the product are you using? On what operating system?

hg HEAD.  Ubuntu 10.04, source-built GCC 4.6.1


Please provide any additional information below.

Just toss in a #include <cstddef> at the top of sweep_context.h to fix.
```

Original issue reported on code.google.com by `genpfa...@gmail.com` on 5 Aug 2011 at 4:03
